sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    options:
        use_select2:   true # disable select2
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
