<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetsRepository extends EntityRepository
{

    public function findBreedAndGender($breed, $gender)
    {
        try {
            return $this->getEntityManager()->createQuery(
                'SELECT pets FROM AppBundle:Pets pets
                 LEFT JOIN pets.breeds breeds
                 WHERE breeds.id = :breed
                 AND pets.gender = :gender
                '
            )
            ->setParameter('breed', $breed)
            ->setParameter('gender', $gender)
            ->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
