services:
    admin.pets:
        class: AppBundle\Admin\PetsAdmin
        arguments: [~, AppBundle\Entity\Pets, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pets }

    admin.breeds:
        class: AppBundle\Admin\BreedsAdmin
        arguments: [~, AppBundle\Entity\Breeds, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Breeds }
