AppBundle\Entity\Pets:
    pets{1..100}:
        pet: <name()>
        description: <paragraph()>
        gender: <numberBetween(1,2)>
        breeds: @breeds<current()>

AppBundle\Entity\Breeds:
    breeds{1..100}:
        breed: <breeds()>
        description: <paragraph()>

AppBundle\Entity\Users:
    admin:
        username: admin
        email: admin@admin.com
        roles: [ROLE_ADMIN]
        password: <encoder('admin', @admin)>
        enabled: 1

    user:
        username: user
        email: user@user.com
        roles: [ROLE_USER]
        password: <encoder('user', @user)>
        enabled: 1
