AppBundle\Entity\Pets:
    pets{1..100}:
        pet: <name()>
        description: <paragraph()>
        gender: <numberBetween(1,2)>
        breeds: @breeds<current()>

AppBundle\Entity\Breeds:
    breeds{1..100}:
        breed: <breeds()>
        description: <paragraph()>
